apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "objecttypen.fullname" . }}
  labels:
    {{- include "objecttypen.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings.djangoSettingsModule | toString | quote }}
  ENVIRONMENT: {{ .Values.settings.environment | default (include "objecttypen.fullname" .) }}
  ALLOWED_HOSTS: "{{ include "objecttypen.fullname" . }},{{ include "objecttypen.fullname" . }}.{{ .Release.Namespace }},{{ .Values.settings.allowedHosts | replace " " "" | toString }}"
  {{- if .Values.tags.redis }}
  CACHE_DEFAULT: {{ printf "%s-master.%s:6379/0" (include "common.names.fullname" .Subcharts.redis) .Release.Namespace | toString | quote }}
  CACHE_AXES: {{ printf "%s-master.%s:6379/0" (include "common.names.fullname" .Subcharts.redis) .Release.Namespace | toString | quote }}
  CACHE_OIDC: {{ printf "%s-master.%s:6379/0" (include "common.names.fullname" .Subcharts.redis) .Release.Namespace | toString | quote }}
  {{ else }}
  CACHE_DEFAULT: {{ .Values.settings.cache.default | toString | quote }}
  CACHE_AXES: {{ .Values.settings.cache.axes | toString | quote }}
  CACHE_OIDC: {{ .Values.settings.cache.oidc | toString | quote }}
  {{- end }}  
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  DB_HOST: {{ .Values.global.settings.databaseHost | default .Values.settings.database.host | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  PGSSLMODE: {{ .Values.settings.database.sslmode | toString | quote }}
  {{ if .Values.settings.debug }}
  DEBUG: "True"
  {{- end }}
  {{ if .Values.settings.disable2fa }}
  DISABLE_2FA: "True"
  {{- end }}
  EMAIL_HOST: {{ .Values.settings.email.host | toString | quote }}
  EMAIL_PORT: {{ .Values.settings.email.port | toString | quote }}
  {{- if .Values.settings.email.username }}
  EMAIL_HOST_USER: {{ .Values.settings.email.username | toString | quote }}
  {{- end }}
  {{- if .Values.settings.email.useTLS }}
  EMAIL_USE_TLS: "True"
  {{- end }}
  {{- if .Values.settings.email.defaultFrom }}
  DEFAULT_FROM_EMAIL: {{ .Values.settings.email.defaultFrom | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVICE_NAME: {{ .Values.settings.elasticapm.serviceName | toString |  quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.master }}
  UWSGI_MASTER:  {{ if .Values.settings.uwsgi.master }}"1"{{ else }}"0"{{ end }}
  {{- end }}
  {{- if .Values.settings.uwsgi.threads }}
  UWSGI_THREADS: {{ .Values.settings.uwsgi.threads  | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.processes }}
  UWSGI_PROCESSES: {{ .Values.settings.uwsgi.processes | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.maxRequests }}
  UWSGI_MAX_REQUESTS: {{ .Values.settings.uwsgi.maxRequests | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.harakiri }}
  UWSGI_HARAKIRI: {{ .Values.settings.uwsgi.harakiri | toString | quote }}
  {{- end }}
  {{ if .Values.configuration.superuser.username }}
  OBJECTTYPE_SUPERUSER_USERNAME: {{ .Values.configuration.superuser.username | toString | quote }}
  OBJECTTYPE_SUPERUSER_EMAIL: {{ .Values.configuration.superuser.email | toString | quote }}
  {{- end }}