{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "objecttypen.fullname" . }}
  labels:
    {{- include "objecttypen.labels" . | nindent 4 }}
stringData:
  DB_PASSWORD: {{ .Values.settings.database.password | toString | quote }}
  SECRET_KEY: {{ .Values.settings.secretKey | toString |  quote }}
  {{- if .Values.settings.sentry.dsn }}
  SENTRY_DSN: {{ .Values.settings.sentry.dsn | toString | quote }}
  {{- end }}
  {{- if .Values.settings.email.password }}
  EMAIL_HOST_PASSWORD: {{ .Values.settings.email.password | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVER_URL: {{ .Values.settings.elasticapm.url | toString |  quote }}
  ELASTIC_APM_SECRET_TOKEN: {{ .Values.settings.elasticapm.token | toString |  quote }}
  {{- end }}
  {{ if .Values.configuration.superuser.username }}
  OBJECTTYPE_SUPERUSER_PASSWORD: {{ .Values.configuration.superuser.password | toString | quote }}
  {{- end }}  
{{- end }}
