apiVersion: v2
name: opennotificaties
description: API voor het routeren van notificaties

type: application
version: 2.1.0-rc.1
appVersion: 1.16.2

dependencies:
  - name: redis
    version: 22.0.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: common
    version: 2.31.4
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
