apiVersion: v2
appVersion: 0.6.0
description: De Referentielijsten API is een generieke API voor eenvoudige herbruikebare lijsten

name: referentielijsten
type: application
version: 0.1.0

dependencies:
  - name: redis
    version: 22.0.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: common
    version: 2.31.4
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: maykin-utils-lib
    version: 0.2.1
    repository: https://maykinmedia.github.io/charts/      