apiVersion: v2
description: Register en API's voor Verzoeken, Taken en Berichten.
name: openvtb
type: application
appVersion: 0.1.0
version: 0.2.0

dependencies:
  - name: redis
    version: 22.0.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: common
    version: 2.31.4
    repository: https://charts.bitnami.com/bitnami
    tags:
    - bitnami-common
