{{- if and .Values.global.configuration.enabled .Values.configuration.enabled .Values.configuration.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.configName" . }}
  labels:
    {{- include "application.configLabels" . | nindent 4 }}
    {{- if .Values.configuration.job.additionalLabels }}
    {{- toYaml .Values.configuration.job.additionalLabels | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    {{- if .Values.configuration.job.annotations }}
    {{- toYaml .Values.configuration.job.annotations | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.configuration.job.backoffLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.configLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.configuration.job.restartPolicy }}
      containers:
        - name: {{ template "application.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "application.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | default (include "application.fullname" .) }}
            - secretRef:
                name: {{ if .Values.existingConfigurationSecret }}{{ .Values.existingConfigurationSecret }}{{ else }}{{ .Values.configurationSecretsName | default (printf "%s-config-secret" (include "application.fullname" .)) }}{{ end }}
            - configMapRef:
                name: {{ include "application.fullname" . }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "application.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.configuration.job.resources | nindent 12 }}
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              /app/src/manage.py setup_configuration --yaml-file /app/configuration/configuration.yaml
          volumeMounts:
            - name: media
              mountPath: /app/private-media
              subPath: {{ .Values.persistence.privateMediaMountSubpath | default (printf "%s/private_media" (include "application.name" .)) }}
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.persistence.mediaMountSubpath | default (printf "%s/media" (include "application.name" .)) }}
            - name: configuration
              mountPath: /app/configuration/
              readOnly: true
            {{- if .Values.extraVolumeMounts }}
            {{- include "application.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.persistence.enabled }}
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "application.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: configuration
          configMap:
            name: {{ include "application.fullname" . }}-configuration
            defaultMode: 0755
        {{- if .Values.extraVolumes }}
        {{- include "application.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
