apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- if .Values.service.additionalLabels }}
    {{- toYaml .Values.service.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- include "application.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
    {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
    {{- end }}
    {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
    {{- end }}
    {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.service.ports }}
    {{- toYaml .Values.service.ports | nindent 4 }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
    {{- end }}
