{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
metadata:
  name: {{ include "application.serviceAccountName" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.additionalLabels }}
    {{- toYaml .Values.serviceAccount.additionalLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
