{{ if and .Values.global.configuration.enabled .Values.configuration.enabled .Values.configuration.job.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "referentielijsten.configName" . }}
  labels:
    {{- include "referentielijsten.configLabels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.configuration.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.configuration.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "referentielijsten.configLabels" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "referentielijsten.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.configuration.job.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | default (include "referentielijsten.fullname" .) }}
            - secretRef:
                name: {{ if .Values.existingConfigurationSecrets }}{{ .Values.existingConfigurationSecrets }}{{ else }}{{ .Values.configurationSecretsName | default (printf "%s-config-secrets" (include "referentielijsten.fullname" .)) }}{{ end }}                
            - configMapRef:
                name: {{ include "referentielijsten.fullname" . }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "referentielijsten.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          resources:
          {{- toYaml .Values.configuration.job.resources | nindent 12 }}
          command:
            - "/bin/bash"
            - "-c"
          args:
          - |
            /usr/bin/envsubst < /app/configuration/configuration.yaml > /tmp/configuration.yaml &&
            /app/src/manage.py setup_configuration --yaml-file /tmp/configuration.yaml
          volumeMounts:
            - name: media
              mountPath: /app/private-media
              subPath: {{ .Values.persistence.privateMediaMountSubpath | default "referentielijsten/private_media" }}
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.persistence.mediaMountSubpath  | default "referentielijsten/media" }}
            - name: configuration
              mountPath: /app/configuration/
              readOnly: true
            {{- if .Values.extraVolumeMounts }}
            {{- include "referentielijsten.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.persistence.enabled }}
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "referentielijsten.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: configuration
          configMap:
            name: {{ include "referentielijsten.fullname" . }}-configuration
            defaultMode: 0755          
        {{- if .Values.extraVolumes }}
        {{- include "referentielijsten.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}