name: Run CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

permissions: {}

jobs:
  linter:
    name: Check Charts Syntax
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add maykin https://maykinmedia.github.io/charts/
          helm repo add elastic https://helm.elastic.co

      - name: Run Helm lint
        run: |
          for CHART_DIR in ./charts/*; do
            if [ -d "$CHART_DIR" ]; then
                helm dependencies build "$CHART_DIR"
                if [ $? -ne 0 ]; then
                    exit 1
                fi

                helm lint "$CHART_DIR"
                if [ $? -ne 0 ]; then
                    exit 1
                fi
            fi
          done

  unittest:
    name: Helm unit tests
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - name: Checkout repository 
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      
      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add maykin https://maykinmedia.github.io/charts/
          helm repo add elastic https://helm.elastic.co

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5

      - name: Install helm-unittest
        env:
          # renovate: datasource=github-releases depName=helm-unittest/helm-unittest
          HELM_UNITTEST_VERSION: v1.1.2
        # TODO: Remove --verify=false once helm-unittest publishes signed releases
        # Tracking: https://github.com/helm-unittest/helm-unittest/issues/362
        run: helm plugin install --verify=false https://github.com/helm-unittest/helm-unittest.git --version "$HELM_UNITTEST_VERSION"

      - name: Run helm-unittest
        run: | 
          helm dependencies build ./charts/maykin-component
          helm unittest ./charts/maykin-component
        
  zizmor:
    name: GitHub Actions Security Analysis with zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
