apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opennotificaties.fullname" . }}
  labels:
    {{- include "opennotificaties.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "opennotificaties.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "opennotificaties.selectorLabels" . | nindent 8 }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opennotificaties.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | default (include "opennotificaties.fullname" .) }}
            - configMapRef:
                name: {{ include "opennotificaties.fullname" . }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "opennotificaties.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /_healthz/
              port: http
              httpHeaders:
                - name: Host
                  value: {{ include "opennotificaties.fullname" . | quote }}
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /_healthz/livez/
              port: http
              httpHeaders:
                - name: Host
                  value: {{ include "opennotificaties.fullname" . | quote }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /_healthz/readyz/
              port: http
              httpHeaders:
                - name: Host
                  value: {{ include "opennotificaties.fullname" . | quote }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.persistence.mediaMountSubpath  | default "opennotificaties/media" }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.persistence.enabled }}
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "opennotificaties.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opennotificaties.workerFullname" . }}
  labels:
    {{- include "opennotificaties.workerLabels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opennotificaties.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
    {{- include "opennotificaties.workerSelectorLabels" . | nindent 8 }}
    {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opennotificaties.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "opennotificaties.workerFullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | default (include "opennotificaties.fullname" .) }}
            - configMapRef:
                name: {{ include "opennotificaties.fullname" . }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "opennotificaties.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.worker.startupProbe.enabled }}
          startupProbe:
            exec: 
              command:
              - /bin/sh
              - -c
              - maykin-common worker-health-check --skip-ping --skip-event-loop-liveness --no-skip-readiness --readiness-file=/app/tmp/celery_worker.ready
            initialDelaySeconds: {{ .Values.worker.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.worker.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.worker.startupProbe.failureThreshold }}
          {{- end }}
  
          {{- if .Values.worker.livenessProbe.enabled }}
          livenessProbe:
            exec: 
              command:
              - /celery_worker_liveness_probe.sh
            initialDelaySeconds: {{ .Values.worker.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.worker.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.worker.livenessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          command:
            - /celery_worker.sh
          volumeMounts:
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.persistence.mediaMountSubpath | default "opennotificaties/media" }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.persistence.enabled }}
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "opennotificaties.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

{{ if .Values.flower.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opennotificaties.flowerFullname" . }}
  labels:
    {{- include "opennotificaties.flowerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      {{- include "opennotificaties.flowerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "opennotificaties.flowerSelectorLabels" . | nindent 8 }}
        {{- with .Values.flower.podLabels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opennotificaties.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "opennotificaties.flowerFullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/celery_flower.sh"]
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | default (include "opennotificaties.fullname" .) }}
            - configMapRef:
                name: {{ include "opennotificaties.fullname" . }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "opennotificaties.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - maykin-common health-check --endpoint=http://localhost:5555/
            initialDelaySeconds: {{ .Values.flower.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.flower.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.flower.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.flower.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.flower.livenessProbe.failureThreshold }}
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - maykin-common health-check --endpoint=http://localhost:5555/
            initialDelaySeconds: {{ .Values.flower.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.flower.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.flower.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.flower.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.flower.readinessProbe.failureThreshold }}
          volumeMounts:
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.persistence.mediaMountSubpath  | default "opennotificaties/media" }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.persistence.enabled }}
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "opennotificaties.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---

# Deployment Beat

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opennotificaties.beatFullname" . }}
  labels:
  {{- include "opennotificaties.beatLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.beat.replicaCount }}
  selector:
    matchLabels:
      {{- include "opennotificaties.beatSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
    {{- include "opennotificaties.beatSelectorLabels" . | nindent 8 }}
    {{- with .Values.beat.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opennotificaties.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "opennotificaties.beatFullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "opennotificaties.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | default (include "opennotificaties.fullname" .) }}
            - configMapRef:
                name: {{ include "opennotificaties.fullname" . }}
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
          command:
            - /celery_beat.sh
          volumeMounts:
            - name: media
              mountPath: /app/media
              subPath: {{ .Values.persistence.mediaMountSubpath  | default "opennotificaties/media" }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          {{- if .Values.beat.probesEnabled }}
          startupProbe:
            exec: 
              command:
              - /bin/sh
              - -c
              - maykin-common beat-health-check --file=/app/tmp/celery_beat.live --max-age=600
            initialDelaySeconds: {{ .Values.beat.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.beat.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.beat.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.beat.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.beat.startupProbe.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - maykin-common beat-health-check --file=/app/tmp/celery_beat.live --max-age=120
            initialDelaySeconds: {{ .Values.beat.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.beat.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.beat.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.beat.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.beat.livenessProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: media
          persistentVolumeClaim:
          {{- if .Values.persistence.enabled }}
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "opennotificaties.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "opennotificaties.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
